import Head from 'next/head'
import Image from 'next/image'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faEnvelope,
  faMobile,
  faLanguage,
  faHandshake,
  faGraduationCap
} from "@fortawesome/free-solid-svg-icons";
import BGI from '../src/components/BGI';
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>

        <title>Sajma Šeper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <div className={styles.backgroundimage}>
            <BGI/>
          </div>
        </main>
    </div> 
  )
}
